import {
  Music,
  Drama,
  Smile,
  Clapperboard,
  Palette,
  BookOpen,
  Mic,
  GraduationCap,
  Briefcase,
  Cpu,
  FlaskConical,
  UtensilsCrossed,
  Wine,
  Users,
  Baby,
  HeartHandshake,
  Trophy,
  Footprints,
  Car,
  Bike,
  Landmark,
  Church,
  PartyPopper,
  Store,
  Plane,
  Sparkles,
  Flower2,
  PawPrint,
  Gamepad2,
  Dice5,
  Building2,
  MoreHorizontal,
} from "lucide-react";

// Íconos para las categorías del Event Creation Engine
// (backend/src/utils/eventCategories.js). Son ids nuevos, distintos de los
// que usa el wizard viejo en frontend/src/lib/eventCategories.js — ver la
// nota de "categorías desincronizadas" del plan de Fase 2.
export const CATEGORY_ICON = {
  MUSICA: Music,
  TEATRO: Drama,
  STAND_UP: Smile,
  CINE: Clapperboard,
  ARTE_EXPOSICIONES: Palette,
  LITERATURA: BookOpen,
  CONFERENCIAS: Mic,
  CURSOS_TALLERES: GraduationCap,
  NEGOCIOS: Briefcase,
  TECNOLOGIA: Cpu,
  CIENCIA: FlaskConical,
  GASTRONOMIA: UtensilsCrossed,
  CATAS_DEGUSTACIONES: Wine,
  EVENTOS_FAMILIARES: Users,
  INFANTILES: Baby,
  SOLIDARIOS: HeartHandshake,
  DEPORTES: Trophy,
  MARATONES: Footprints,
  AUTOMOVILISMO: Car,
  MOTOCICLISMO: Bike,
  TRADICION_CAMPO: Landmark,
  RELIGIOSOS: Church,
  FIESTAS: PartyPopper,
  FERIAS: Store,
  TURISMO: Plane,
  BIENESTAR: Sparkles,
  YOGA_MEDITACION: Flower2,
  MASCOTAS: PawPrint,
  GAMING: Gamepad2,
  JUEGOS_DE_MESA: Dice5,
  INSTITUCIONALES: Building2,
  OTRO: MoreHorizontal,
};

export function getCategoryIcon(categoryId) {
  return CATEGORY_ICON[categoryId] ?? MoreHorizontal;
}
